# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lotka_volterra_generator <- function(theta, y1_min, y1_max, y2_min, y2_max) {
    .Call(`_smcdar_lotka_volterra_generator`, theta, y1_min, y1_max, y2_min, y2_max)
}

